sudo: required
language: cpp
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - libglew-dev
      - libboost-filesystem-dev 
      - libboost-system-dev
      - libboost-chrono-dev

before_install:
  - bash .travis.sh travis_before_install

script:
  - bash .travis.sh travis_script
