sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - ubuntu-sdk-team
    packages:
      - gcc-5
      - g++-5
      - cmake
      - libglew-dev
      - libboost-filesystem-dev 
      - libboost-system-dev
      - libboost-chrono-dev
      - libopenal-dev
      - qt5-qmake 
      - qtbase5-dev

before_install:
  - bash .travis.sh travis_before_install

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - export QT_SELECT="qt5"
  - qmake --version
  
script:
  - bash .travis.sh travis_script
