version: '{build}'
environment:
  BUILD_TYPE: Visual Studio 14 2015 Win64
  TARGET_OS: WIN32

  matrix:
  - CONFIG_TYPE: Release
    BUILD_UI: NATIVE
  - CONFIG_TYPE: Release
    BUILD_UI: QT
build_script:
- cmd: >-
    git clone -q https://github.com/jpd002/Play-Build.git C:\Projects\Play-Build

    cd C:\Projects\Play-Build

    git submodule update -q --init --recursive

    git submodule foreach -q "git checkout -q master"

    cd Dependencies

    git submodule update --init

    cd ..

    rd /S /Q Play

    move C:\Projects\Play Play

    cd Play\build_cmake

    mkdir build

    cd build

    if "%BUILD_UI%"=="NATIVE" ( cmake .. -G"%BUILD_TYPE%" -DCMAKE_BUILD_TYPE=%CONFIG_TYPE% )

    if "%BUILD_UI%"=="QT" ( cmake .. -G"%BUILD_TYPE%" -DCMAKE_BUILD_TYPE=%CONFIG_TYPE% -DUSE_QT:BOOL=on -DCMAKE_PREFIX_PATH="C:\Qt\5.8\msvc2015_64" )

    cmake --build . --config %CONFIG_TYPE%
