name: Build Linux

on: [push, pull_request]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Force Fetch Git Tags
      run: git fetch --tags --force
    - name: Set SHORT_HASH
      run: echo "::set-output name=VALUE::${LONG_HASH:0:8}"
      id: short_hash
      env:
        LONG_HASH: ${{ github.sha }}
    - name: Build Docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: build_docker/x86_64-cross_compile/armv7/Dockerfile
        push: false
        tags: cross_compile-armv7
    - name: Build & Test
      uses: addnab/docker-run-action@v2
      with:
        image: cross_compile-armv7
        options: -v ${{ github.workspace }}:/workdir
        run: |
            mkdir build
            cmake -Bbuild -H. -DCMAKE_TOOLCHAIN_FILE=./build_docker/x86_64-cross_compile/armv7/toolchain.cmake -DENABLE_AMAZON_S3=off -DQt5_DIR=/usr/lib/arm-linux-gnueabihf/cmake/Qt5/ -DUSE_GLES=on
            cmake --build build
